checkbook/urls.py
from django.urls import path
from .views import CheckCreate, CheckDelete, CheckUpdate, CategoryPopUp
from .views import CategoryCreate, CategoryDelete, CategoryUpdate, cat_pie, CatData
from . import views
#from . import admin

urlpatterns = [
    path('', views.index, name='index'),
    path('api/data', cat_pie, name='api-data'),
    path('api/chart/data', CatData.as_view()),

    path('calendar', views.fmlCalendar, name='calendar'),
    path('calendar/<int:aYear>/<int:aMonth>/', views.fmlCalendar, name='calendarNav'),

    path('checkbookList', views.checkbookList, name='checkbook'),
    path('checkbookMonth', views.checkbookMonth, name='checkbook-month'),
    path('checkbookMonth/<int:aYear>/<int:aMonth>/', views.checkbookMonth, name='checkbook-monthNav'),

    path('checks/', views.CheckListView.as_view(), name='check-list'),
    path('check/add/', views.CheckCreate.as_view(), name='check-add'),
    path('check/<int:pk>/', views.CheckUpdate.as_view(), name='check-detail'),
    path('check/<int:pk>/delete/', CheckDelete.as_view(), name='check-delete'),
    path('check/addbill/', views.addCheckBills, name='add-bill'),

    path('categories/', views.CategoryListView.as_view(), name='category-list'),
    #path('category/addcpu/', views.CategoryCreate.as_view(), name='category-cpu'),
    path('category/addcpu/', views.CategoryPopUp.as_view(), name='category-cpu'),
    path('category/add/', views.CategoryCreate.as_view(), name='category-add'),
    path('category/<int:pk>/', views.CategoryUpdate.as_view(), name='category-detail'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category-delete'),
]

#this is a comment to test git update

fmlcalendar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('checkbook/', include('checkbook.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/checkbook/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

checkbook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Check(models.Model):

    """
    Model representing a checkbook transaction.
    """
    check_type = (('CR', 'credit'),('DR', 'debit'),('SV', 'savings'),('DT', 'debt reduction'),)
    #theuser = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    dater = models.DateField(help_text=' .the date of the transaction')
    type = models.CharField(max_length=2, choices=check_type, help_text=' .credit or debit')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, help_text=' .description')
    amount = models.IntegerField(default=0, help_text=' .amount')
    cleared = models.BooleanField(help_text=' .cleared with the bank?')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["dater"]

    def __str__(self):
        return f'{self.dater} {self.name} {self.amount}'

    def short_description(self):
        return self.name[:25]

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this transaction.
        """
        return reverse('check-detail', kwargs={'pk': self.pk})

class Category(models.Model):

    """
    Model representing a Category.
    """
    name = models.CharField(max_length=100, help_text=' .category name')
    frequency = models.CharField(max_length=10, null=True, blank=True, help_text=' .M(monthly) or W(weekly)')
    budget = models.IntegerField(default=0, help_text=' .budgeted amount by frequency' )

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular category instance.
        """
        #return reverse('category-detail', args=[str(self.id)])
        return reverse('category-detail', kwargs={'pk': self.pk})

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}'.format(self.name)

checkbook/forms.py
#from django.forms import ModelForm
from django import forms
from .models import Category

class AddBills(forms.Form):
    """
    Form representing a add bill transaction.
    """
    check_type = (('CR', 'credit'),('DR', 'debit'),('SV', 'savings'),('DT', 'debt reduction'),)

    dater = forms.DateField(label='Date', help_text=' .the date of the transaction')
    type = forms.ChoiceField(choices=check_type, help_text=' .credit or debit')
    category = forms.ModelChoiceField(Category.objects.values('name').distinct(), empty_label=None)
    name = forms.CharField(max_length=100, help_text=' .description')
    amount = forms.IntegerField(help_text=' .amount')
    cleared = forms.BooleanField(help_text=' .cleared with the bank?')
    addagain = forms.BooleanField(label='Add again', help_text=' .create a re-occuring bill?')

checkbook/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django import forms

#function pagination
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Check, Category

from django_addanother.widgets import AddAnotherWidgetWrapper
from django_addanother.views import CreatePopupMixin

from .calendar import CheckbookCalendar
from calendar import monthrange

from django.utils.html import conditional_escape as esc
from django.utils.safestring import mark_safe
from datetime import date, datetime

#index
from django.db.models import Max

#pie
from django.http import JsonResponse

#rest framework
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth import get_user_model

User = get_user_model()

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_checks=Check.objects.all().count()
    forecast_date = Check.objects.all().aggregate(Max('dater'))
    forecast_bal=Check.objects.all().aggregate(Sum('amount'))
    today_bal=Check.objects.filter(dater__lte=date.today()).aggregate(Sum('amount'))
    cat_data = Check.objects.filter(type='DR').values_list('category__name').annotate(cat_total = Sum('amount')*-1).order_by()

    cat_label=[]
    cat_value=[]
    for i in cat_data:
        cat_label.append((i[0]))
        cat_value.append(i[1])
    #    cat_value.append(y)
        #cat_label.append(str(x.category__name))
    #    cat_value.append(x.cat_total)
    str(cat_label).replace("'", '"')

    #cat_data = Check.objects.annotate(cat_total=Sum("amount"))
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'checkbook/index.html',
        context={'num_checks':num_checks,'forecast_bal':forecast_bal,
            'today_bal':today_bal,'num_visits':num_visits,
            'forecast_date':forecast_date, 'today':date.today(),
            'cat_data':cat_data, 'cat_label':cat_label, 'cat_value':cat_value},
    )

def cat_pie(request, *args, **kwargs):
    data = {
        "Housing": 1031,
        "Utilities": 129,
        "Living Expenses": 311,
    }
    return JsonResponse(data)

class CatData(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        cat_sum = Check.objects.filter(category__name="Housing").aggregate(Sum('amount'))
        labels = ["Category", "Amount"]
        default_items = [cat_sum]
        data = {
                "labels": labels,
                "default": default_items,
        }
        return Response(data)


def checkbookList(request):
    check_list = Check.objects.all()
    #checks = Check.objects.all()
    page = request.GET.get('page', 1)

    balance = 0
    #for chk in checks:
    for chk in check_list:
        balance += chk.amount
        chk.balance = balance

        if chk.cleared:
            chk.cleared = '\u221A'
        else:
            chk.cleared = '-'

    paginator = Paginator(check_list, 20)
    try:
        checks = paginator.page(page)
    except PageNotAnInteger:
        checks = paginator.page(1)
    except EmptyPage:
        checks = paginator.page(paginator.num_pages)

    return render(request, 'checkbook/checkbook.html', {'checks': checks})

def checkbookMonth(request, aYear=date.today().year , aMonth=date.today().month):

    #set up month and year navigation
    curYear = int(aYear)
    curMonth = int(aMonth)
    fromMonth = date(aYear, aMonth, 1)
    toMonth = date(aYear, aMonth, monthrange(aYear, aMonth)[1])

    PreviousYear = curYear
    PreviousMonth = curMonth - 1
    if PreviousMonth == 0:
        PreviousMonth = 12
        PreviousYear = curYear - 1
    NextYear = curYear
    NextMonth = curMonth + 1
    if NextMonth == 13:
        NextMonth = 1
        NextYear = curYear + 1


    #get all objects, add balance to checkbook in realtime
    check_list = Check.objects.all()
    balance = 0
    #for chk in checks:
    for chk in check_list:
        balance += chk.amount
        chk.balance = balance

        if chk.cleared:
            chk.cleared = '\u221A'
        else:
            chk.cleared = '-'

    return render(request, 'checkbook/checkbookNEW.html', {'checks' : check_list,
                                                       'Month' : curMonth,
                                                       'MonthName' : named_month(curMonth),
                                                       'Year' : curYear,
                                                       'PreviousMonth' : PreviousMonth,
                                                       'PreviousMonthName' : named_month(PreviousMonth),
                                                       'PreviousYear' : PreviousYear,
                                                       'NextMonth' : NextMonth,
                                                       'NextMonthName' : named_month(NextMonth),
                                                       'NextYear' : NextYear,
                                                       'fromMonth' : fromMonth,
                                                       'toMonth' :toMonth
                                                   })




# generate bills, or reoccurring check CheckEntries
from .forms import AddBills
def addCheckBills(request):

    if request.method == 'POST':
        pass
    else:
        form = AddBills()

    return render(request, 'checkbook/bills.html', {'form' : form})


from django.views import generic

class CheckListView(generic.ListView):
    model = Check
    paginate_by = 25

class CheckDetailView(generic.DetailView):
    model = Check

class CheckForm(forms.ModelForm):
    class Meta:
        model = Check
        fields = ['dater', 'type', 'category', 'name', 'amount', 'cleared']
        widgets = {
            'dater': forms.TextInput(attrs={'class':'datepicker', 'autocomplete': 'off',}),
            'category': AddAnotherWidgetWrapper(
                forms.Select,
                reverse_lazy('category-cpu'),)
        }

class CheckCreate(CreateView):
    form_class = CheckForm
    model = Check
    success_url = reverse_lazy('checkbook')

class CheckUpdate(UpdateView):
    model = Check
    success_url = reverse_lazy('checkbook')
    fields = ['dater', 'type', 'category', 'name', 'amount', 'cleared']
    #template_name_suffix = '_update_form'

class CheckDelete(DeleteView):
    model = Check
    success_url = reverse_lazy('checkbook')

# should be able to remove check-list from program now.

# Category views
# --------------------------------------------
class CategoryListView(generic.ListView):
    model = Category
    paginate_by = 20

class CategoryDetailView(generic.DetailView):
    model = Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'frequency', 'budget']

class CategoryPopUpForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'frequency', 'budget']


#class CategoryCreate(CreatePopupMixin, CreateView):
class CategoryCreate(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('category-list')

class CategoryPopUp(CreatePopupMixin, CreateView):
    model = Category
    form_class = CategoryPopUpForm
    template_name_suffix = '_popup_form'

class CategoryUpdate(UpdateView):
    model = Category
    success_url = reverse_lazy('category-list')
    fields = ['name', 'frequency', 'budget']
    template_name_suffix = '_update_form'

class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('category-list')

# calendar views
# - - - - - - - -
from django.http import HttpResponse
from calendar import HTMLCalendar
from django.utils.safestring import mark_safe
import calendar

#def fmlCalendar(request):
#    c = calendar.HTMLCalendar(calendar.MONDAY)
#    y = date.today().year
#    m = date.today().month
#    myCal = c.formatmonth(y,m)
#    return render(request, 'checkbook/calendar.html', {'fmlCalendar': mark_safe(myCal)})

def named_month(pMonthNumber):
    """
    Return the name of the month, given the month number
    """
    return date(1900, pMonthNumber, 1).strftime('%B')

def fmlCalendar(request, aYear=date.today().year , aMonth=date.today().month):
    #cal = calendar.HTMLCalendar(calendar.MONDAY)
    curYear = int(aYear)
    curMonth = int(aMonth)
    #fmlCal = cal.formatmonth(curYear,curMonth)

    CalendarFromMonth = datetime(aYear, aMonth, 1)
    CalendarToMonth = datetime(aYear, aMonth, monthrange(aYear, aMonth)[1])
    CheckEntries = Check.objects.filter(dater__gte=CalendarFromMonth, dater__lte=CalendarToMonth)
    fmlCal = CheckbookCalendar(CheckEntries).formatmonth(aYear, aMonth)

    PreviousYear = curYear
    PreviousMonth = curMonth - 1
    if PreviousMonth == 0:
        PreviousMonth = 12
        PreviousYear = curYear - 1
    NextYear = curYear
    NextMonth = curMonth + 1
    if NextMonth == 13:
        NextMonth = 1
        NextYear = curYear + 1

    return render(request, 'checkbook/calendar.html', {'fmlCalendar' : mark_safe(fmlCal),
                                                       'Month' : curMonth,
                                                       'MonthName' : named_month(curMonth),
                                                       'Year' : curYear,
                                                       'PreviousMonth' : PreviousMonth,

checkbook/templates/checkbook/bills.html
{% extends "base_generic.html" %}

{% block content %}
<h2>.fml finance .add transaction</h2>
<br/>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>
{% endblock %}

checkbook/templates/checkbook/category_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>.fml finance .delete category</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

checkbook/templates/checkbook/category_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>. category: {{ category.name }}</h1>

  <p><strong>category:</strong> {{ category.name }}</p>
  <p><strong>budget frequency:</strong> {{ category.frequency }}</p>
  <p><strong>budget amount:</strong> {{ category.budget }}</p>
  
{% endblock %}

checkbook/templates/checkbook/category_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .add category</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>

{% endblock %}

checkbook/templates/checkbook/category_popup_form.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

{% block extrahead %}
  {{ form.media }}
{% endblock %}

{% block content %}

    <h2>.fml finance .popup category</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add" />
        {{ form.media }}
    </form>

{% endblock %}

checkbook/templates/checkbook/category_update_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .update category</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>

{% endblock %}

checkbook/templates/checkbook/check_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>.fml finance .delete transaction</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

checkbook/templates/checkbook/check_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ check.name }}</h1>

  <p><strong>date:</strong> {{ check.dater }}</p>
  <p><strong>name:</strong> {{ check.name }}</p>
  <p><strong>type:</strong> {{ check.type }}</p>
  <p><strong>category:</strong> <a href="{% url 'category-detail' check.category.pk %}">{{ check.category }}</a></p>
  <p><strong>amount:</strong> {{ check.amount }}</p>
  <p><strong>is cleared:</strong> {{ check.cleared }}</p>

{% endblock %}

<a href="{% url 'check-update' %}">update transaction</a>

checkbook/templates/checkbook/check_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .add transaction</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>

{% endblock %}

<script>
  $(function() {
      $( "#id_dater" ).datepicker();
  });
</script>

checkbook/templates/checkbook/check_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h2>.fml finance .checkbook</h2>

    <a href="{% url 'check-add' %}">add new</a>

    {% if check_list %}
    <ul>

      {% for check in check_list %}
      <li>
        {{ check.dater|date:'Y M d' }}:
        <a href="{{ check.get_absolute_url }}"> {{ check.name }}</a> ({{check.amount}})
        <a href="{% url 'check-delete' check.id %}">delete</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no checks in the checkbook.</p>
    {% endif %}

{% endblock %}

checkbook/templates/checkbook/check_update_form.html
{% extends "base_generic.html" %}

{% block content %}

    <h2>.fml finance .update transaction</h2>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>

{% endblock %}

<script>
  $(function() {
      $( "#id_dater" ).datepicker();
  });
</script>

checkbook/templates/checkbook/checkbook.html
{% extends "base_generic.html" %}

{% block extrahead %}
  {{ form.media }}
{% endblock %}

{% block content %}
    <h2>.fml finance .register</h2>

    <a href="{% url 'check-add' %}">add new</a>

    {% if checks %}

    <table class="greyGridTable">
      <thead>
        <tr>
          <th>date</th>
          <th>cleared</th>
          <th>description</th>
          <th>category</th>
          <th>amt</th>
          <th>bal</th>
          <th></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>date</td>
          <td>cleared</td>
          <td>description</td>
          <td>category</td>
          <td>amt</td>
          <td>bal</td>
          <td></td>
        </tr>
      </tfoot>
        {% for check in checks %}
        <tr>
          <td>{{ check.dater|date:'Y M d' }}</td>
          <td>{{check.cleared}}</td>
          <td><a href="{{ check.get_absolute_url }}"> {{ check.name }}</a></td>
          <td>{{check.category}}</td>
          <td>{{check.amount}}</td>
          <td>{{check.balance}}</td>
          <td><a href="{% url 'check-delete' check.id %}">delete</a></td>
        </tr>
        {% endfor %}
    </table>

    {% else %}
      <p>There are no checks in the checkbook.</p>
    {% endif %}

    {% if checks.has_other_pages %}
      <ul class="pagination">
        {% if checks.has_previous %}
          <li><a href="?page={{ checks.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in checks.paginator.page_range %}
          {% if checks.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if checks.has_next %}
          <li><a href="?page={{ checks.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}

{% endblock %}

checkbook/templates/checkbook/checkbookNEW.html
{% extends "base_generic.html" %}

{% block extrahead %}
  {{ form.media }}
{% endblock %}

{% block content %}
    <h2>.fml finance .checkbook <small>{{fromMonth}} -- {{toMonth}}</small></h2>


    <table width="97%">
      <tr>
        <td width="30%" align="left">
          &lt;&lt; <a href="{% url 'checkbook-monthNav' PreviousYear PreviousMonth%}">{{PreviousMonthName}} {{PreviousYear}}</a>
        </td>
        <td width="30%" align="center"><a href="{% url 'checkbook-month' %}"">{{MonthName}} {{Year}}</a></td>
        <td width="30%" align="right">
          <a href="{% url 'checkbook-monthNav' NextYear NextMonth%}">{{NextMonthName}} {{NextYear}}</a> &gt;&gt;
        </td>
      </tr>
    </table>
    <br/>
    <a href="{% url 'check-add' %}">add new</a>

    {% if checks %}
    <table class="greyGridTable">
      <thead>
        <tr>
          <th>date</th>
          <th>cleared</th>
          <th>description</th>
          <th>category</th>
          <th>amt</th>
          <th>bal</th>
          <th></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>date</td>
          <td>cleared</td>
          <td>description</td>
          <td>category</td>
          <td>amt</td>
          <td>bal</td>
          <td></td>
        </tr>
      </tfoot>
        {% for check in checks %}
          {% if check.dater >= fromMonth and check.dater <= toMonth %}
          <tr>
            <td>{{ check.dater|date:'Y M d' }}</td>
            <td>{{check.cleared}}</td>
            <td><a href="{{ check.get_absolute_url }}"> {{ check.name }}</a></td>
            <td>{{check.category}}</td>
            <td>{{check.amount}}</td>
            <td>{{check.balance}}</td>
            <td><a href="{% url 'check-delete' check.id %}">delete</a></td>
          </tr>
          {% endif %}
        {% endfor %}
    </table>
    {% else %}
      <p>There are no checks in the checkbook.</p>
    {% endif %}

{% endblock %}

checkbook/templates/checkbook/index.html
{% extends "base_generic.html" %}

<script>
{% block jquery %}
var end_point = '/api/chart/data/'
var defaultData = []
var labels = [];
$.ajax({
  method: "GET"
  url: end_point
  console.log("in ajax call")
  success: function(data){
    labels = data.labels
    defaultData = data.default
    setChart()
  },
  error: function(error_data){
    console.log("error")
    console.log(error_data)
  }
})

function setChart(){
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["User", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [1, 23, 2, 3, 12, 2],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

{% endblock %}
</script>

{% block content %}
<div class-"header">
  <h2>. fml finance .dashboard</h2>
  <!-- this is a comment -->
</div>
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-sm-4" style="padding-right:20px; border-right: 2px solid #ccc;">
        <h4>Todays Balance:</h4>
        <h5>{{ today }}</h5>
        <h5>${{ today_bal.amount__sum }}</h5>
      </div>
      <div class="col-sm-4" style="padding-right:20px; border-right: 2px solid #ccc;">
        <h4>Forecasted Balance as of:</h4>
        <h5>{{ forecast_date.dater__max }}</h5>
        <h5>${{ forecast_bal.amount__sum }}</h5>
      </div>
      <div class="col-sm-4">
        <h4>Upcoming Bills:</h4>

      </div>
    </div>
    <div class="row">
      <div class="col-sm-12" style="padding-right:20px;">
      <hr />
      <h4>Category Spending:</h4>

        <canvas id="myChart" width="800" height="350"></canvas>
        <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: {{ cat_label|safe }},
                datasets: [{
                    label: '$ of spending',
                    data: {{ cat_value }},
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            }
        });
        </script>
        <i>...focusing on lowering your spending on 1 or more categories can
        significantly improve your
        financial outlook</i>
    </div>
  </div>
</div>
  <br>
  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times. {% endif %}
    You've got some issues buddy.</p>

{% endblock %}